// <auto-generated />
using System;
using DeerStand.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeerStand.Infrastructure.Migrations
{
    [DbContext(typeof(DeerStandDbContext))]
    partial class DeerStandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeerStand.Infrastructure.Data.ActiveCheckIn", b =>
                {
                    b.Property<Guid>("StandId")
                        .HasColumnType("uuid")
                        .HasColumnName("stand_id");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("checked_in_at");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_id");

                    b.HasKey("StandId");

                    b.HasIndex("ProfileId");

                    b.ToTable("active_check_ins", (string)null);
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("log_type");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_id");

                    b.Property<Guid?>("StandId")
                        .HasColumnType("uuid")
                        .HasColumnName("stand_id");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StandId");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.CheckInHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTimeOffset>("CheckedOutAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("checked_out_at");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("StandId")
                        .HasColumnType("uuid")
                        .HasColumnName("stand_id");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StandId");

                    b.ToTable("check_in_history", (string)null);
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.ClubMember", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<string>("ProfileId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("ClubId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("club_members", (string)null);
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.Stand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("stands", (string)null);
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.ActiveCheckIn", b =>
                {
                    b.HasOne("DeerStand.Infrastructure.Data.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeerStand.Infrastructure.Data.Stand", "Stand")
                        .WithOne("ActiveCheckIn")
                        .HasForeignKey("DeerStand.Infrastructure.Data.ActiveCheckIn", "StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.ActivityLog", b =>
                {
                    b.HasOne("DeerStand.Infrastructure.Data.Club", "Club")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeerStand.Infrastructure.Data.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeerStand.Infrastructure.Data.Stand", "Stand")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Club");

                    b.Navigation("Profile");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.CheckInHistory", b =>
                {
                    b.HasOne("DeerStand.Infrastructure.Data.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeerStand.Infrastructure.Data.Stand", "Stand")
                        .WithMany("CheckInHistory")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.Club", b =>
                {
                    b.HasOne("DeerStand.Infrastructure.Data.Profile", "Owner")
                        .WithMany("OwnedClubs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.ClubMember", b =>
                {
                    b.HasOne("DeerStand.Infrastructure.Data.Club", "Club")
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeerStand.Infrastructure.Data.Profile", "Profile")
                        .WithMany("Memberships")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.Stand", b =>
                {
                    b.HasOne("DeerStand.Infrastructure.Data.Club", "Club")
                        .WithMany("Stands")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.Club", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Members");

                    b.Navigation("Stands");
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.Profile", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("OwnedClubs");
                });

            modelBuilder.Entity("DeerStand.Infrastructure.Data.Stand", b =>
                {
                    b.Navigation("ActiveCheckIn");

                    b.Navigation("ActivityLogs");

                    b.Navigation("CheckInHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
