server {
  listen 80;
  server_name _;

  location / {
    root /usr/share/nginx/html;
    autoindex on;
    add_header Access-Control-Allow-Origin *;
    # Required for HTTP Range requests used by pmtiles
    add_header Accept-Ranges bytes;
  }
}
